project:
  type: manuscript

manuscript:
  article: index.qmd

format:
  html:
    # code-fold: true
    code-tools: true
    comments:
      hypothesis: true
    toc: true
    toc-location: left

execute:
  freeze: false